print("Start")

bilangan_pertama = int(input("Masukkan bilangan pertama: "))
bilangan_kedua = int(input("Masukkan bilangan kedua: "))
hasil_jumlah = bilangan_pertama + bilangan_kedua
hasil_pengurangan = bilangan_pertama - bilangan_kedua
hasil_modulus = bilangan_pertama % bilangan_kedua

print("Hasil penjumlahan adalah:", hasil_jumlah)
print("Hasil pengurangan adalah:", hasil_pengurangan)
print("Hasil modulus adalah:", hasil_modulus)
print("End")